export const product =  [ 
    {
        id:"1",
        title: "crema para cuerpo",
        price: 14990,
        stock: 30,
        category: "skincare",
        description: "crema humectante con niacidamina ",
        imageUrl: "",
    },
    {
        id:"2",
        title: "Crema contorno de ojos",
        price: 15990,
        stock: 30,
        category: "skincare",
        description: "crema con retinol y niacidamina. ",
        imageUrl: "",
    },
    {
        id:"3",
        title: "crema para rostro",
        price: 22000,
        stock: 30,
        category: "skincare",
        description: "crema para rostro con niacidamida y centella asiatica ",
        imageUrl: "",
    },
    {
        id:"4",
        title: "Aceite facial",
        price: 17990,
        stock: 25,
        category: "skincare",
        description: "Aceite intensivo para las manchas con niacidamida y centella asiatica",
        imageUrl: "",
    },
    {
        id:"5",
        title: "kit rostro piel sensible",
        price: 14990,
        stock: 30,
        category: "skincare",
        description: "kit para rostro. Con niacidamida, vitamina C y centella asiatica",
        imageUrl: "",
    },
    {
        id:"6",
        title: "Toner para el rostro",
        price: 12990,
        stock: 30,
        category: "skincare",
        description: "Toner para piel sensible, grasa. Calmante y propiedades exfoliantes",
        imageUrl: "",
    },
    {
        id:"7",
        title: "Paleta de sombras",
        price: 26990,
        stock: 15,
        category: "maquillaje",
        description: "Paleta de sombras tonos cherry ",
        imageUrl: "",
    },
    {
        id:"8",
        title: "kit labiales, esmaltes y sombras de ojos.",
        price: 32990,
        stock: 20,
        category: "maquillaje",
        description: "crema humectante con niacidamina ",
        imageUrl: "",
    },
    {
        id:"9",
        title: "Tinte de labios.",
        price: 8990,
        stock: 20,
        category: "maquillaje",
        description: "Tinte de labios. Diferentes colores. ",
        imageUrl: "",
    },
    {
        id:"10",
        title: "Set de labiales",
        price: 17990,
        stock: 20,
        category: "maquillaje",
        description: "Set de labiales humectantes. Larga duración.",
        imageUrl: "",
    },
    {
        id:"11",
        title: "Iluminador",
        price: 16990,
        stock: 20,
        category: "maquillaje",
        description: "Iluminador larga duración.",
        imageUrl: "",
    },
    {
        id:"12",
        title: "Sombra de ojos con brillos.",
        price: 7990,
        stock: 20,
        category: "maquillaje",
        description: "Sombra de diferentes colores con brillos.",
        imageUrl: "",
    }
] 
